### ISSUE TITLE
DOCS: Note fields must be listed in the command in the same order as they are entered in the survey

### ISSUE THREAD

**Issue by jpeacock29** [grezniczek/redcap_field_shuffle#2]
In order for the blocking functionality to work, the fields must be listed in the shuffle command in the same order they are found on the survey page. For example, if the survey page list the fields A, B, C, the following command will work

@SHUFFLE-FIELDS-SURVEY="(A, B), C"

However, this command will fail by not respecting the blocking of A and B:

@SHUFFLE-FIELDS-SURVEY="(B, A), C"

**Comment by grezniczek** [comment]
@jpeacock29 - Thanks for bringing this up. I guess the use case of changing the field order of isolated groups did not come up as a use case originally. I have changed the way the mapping is calculated to support this (well, actually this was a bug, I guess).

I have submitted a new version 1.1.1 to the EM Repository.

**Comment by jpeacock29** [comment]
Wow, thank you so much for the quick fix! Yes, we ran in to this accidentally as we were just listing the fields we wanted, without thinking about the order in which we originally listed them, and then couldn't figure out why it didn't work for a while.

I really appreciate your supporting this package; it's so valuable!
